x <- 5+7
y <- x-3
c(1, 1, 9, 3, 14)
z <- c(1,1,9,3,14)
length(x)
length(x); length(y); length(z)
getwd()
list.files()
rm(list=ls())
args(list.files)
list.files(path = "c:/")
list.files()
file.rename()
setwd()
getwd()
path <- file.path("Users","davemeteore", "Documentos", "GitHub", "R-basico", fsep="/")
setwd(path)
getwd()
dir.create("materias/filosofia")
